version: 2.1
orbs:
  # The python orb contains a set of prepackaged CircleCI configuration you can use repeatedly in your configuration files
  # Orb commands and jobs help you with common scripting around a language/tool
  # so you dont have to copy and paste it everywhere.
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/python
  python: circleci/python@1.5.0
jobs:
  build-and-test:
    docker:

      - image: cimg/python:3.12.2
    # Service container image
      - image: cimg/postgres:16.0
        environment:
          POSTGRES_USER: user
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-client
      - run: whoami
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - python/install-packages:
          pkg-manager: pip
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r testproject/requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            python3 testproject/manage.py collectstatic
            python3 testproject/manage.py test wagtail_transcription.tests
      - store_artifacts:
          path: test-reports/
          destination: python_app

workflows: {}
#  wagtail_transcription-test: # This is the name of the workflow, feel free to change it to better match your workflow.
#    # Inside the workflow, you define the jobs you want to run.
#    jobs:
#      - build-and-test